# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Kevan
email: m@kevan.tv
description: >
  Product managment, user experience, design & development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kevan.tv" # the base hostname & protocol for your site
author: Matt Kevan

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  work:
    output: true
    permalink: /work/:path/
  articles:
    output: true
    permalink: /articles/:path/

defaults:
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "case-study"
      title: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      description: ""
      tags: []
      author: "Matt Kevan"
  -
    scope:
      path: ""
      type: "resource"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "articles"
    values: 
      layout: "post"
      lead: ""
      tags: []
      author: "Matt Kevan"
