# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Kevan
email: m@kevan.tv
description: >
  UX, design, art & code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kevan.tv" # the base hostname & protocol for your site
author: Matt Kevan

# Build settings
markdown: kramdown

sass:
  style: compressed
  
gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

permalink: pretty

feed:
  excerpt_only: true

collections:
  art:
    output: true
    permalink: /art/:path/
  work:
    output: true
    work: /work/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
      author: "Matt Kevan"
  -
    scope:
      path: ""
      type: "art"
    values: 
      layout: "post"
      author: "Matt Kevan"
  -
    scope:
      path: ""
      type: "work"
    values: 
      layout: "post"