---
upload_path: "/images"
frontmatter_file_url_template: "/images"
body_file_url_template: "{{ site.baseurl }}/images"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
