---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _work
  label: Work
  create: all
  match: "**/*"
- type: directory
  path: _articles
  label: Articles
  create: all
  match: "**/*"
upload_dir: images
public_path: "{{ site.baseurl }}/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
